embeddings:
  path: sentence-transformers/nli-mpnet-base-v2

nop:

client.Weaviate:

workflow:
  index:
    batch: 2500
    tasks:
    - action: [nop, transform]
      merge: hstack
      unpack: False
    - action: client.Weaviate
      unpack: False
  search:
    tasks:
    - action: transform
    - action: client.Weaviate
      args: [search]
 